[variables]
NIXPACKS_PHP_NGINX_CONFIG = "conf/nginx.conf"

[phases.setup]
nixPkgs = ["...", "nano"]

[phases.install]
cmds = [
    "mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx",
    "composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader --ignore-platform-reqs",
    "npm i"
]
